M48
; DRILL file {KiCad 9.0.0} date 2025-04-14T10:38:39-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-14T10:38:39-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.500
%
G90
G05
T1
X124.5Y-93.0
X125.0Y-49.0
X129.0Y-133.0
X146.0Y-71.5
X176.0Y-49.0
T2
X175.243Y-111.998
M30
