M48
; DRILL file {KiCad 9.0.0} date 2025-04-14T10:18:10-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-14T10:18:10-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.500
%
G90
G05
T1
X61.0Y-55.7
X112.0Y-55.7
X201.0Y-55.7
T2
X93.0Y-68.8
X150.9Y-68.8
X151.0Y-91.8
M30
